gpg-tar can extract

diff --git a/gpg-tar b/gpg-tar
--- a/gpg-tar
+++ b/gpg-tar
@@ -1,11 +1,28 @@
 #!/bin/bash
+gethelp () {
+    printf "gpg-tar <command> <file>\n"
+    printf "<command>\n"
+    printf "    c: create new archive\n"
+    printf "    t: list files in archive\n"
+    printf "    x: extract files from archive\n"
+}
 if [ ! -e ~/.recipient ] ; then
-        printf "recipient key required\n"
-        printf "try \"gpg --export -o ~/.recipient <you@yourdomain>\"\n"
-        exit 1
-elif [ -z $1 ] ; then
-	printf "gpg-tar <file> or <directory>\n"
+	printf "recipient key required\n"
+	printf "try \"gpg --export -o ~/.recipient <you@yourdomain>\"\n"
+    exit 1
+elif [ -z $2 ] ; then
+	gethelp
 	exit 1
 fi
-tar -cvh --exclude-vcs $1 | gpg -e -o $1.tar.pgp --set-filename "$1.tar" -F ~/.recipient
-printf "done\n"
+case "$1" in
+    [cau] )
+        tar -cvh --exclude-vcs $2 | gpg -e -o $2.tar.pgp --set-filename "$2.tar" -F ~/.recipient ;;
+    [tl] ) 
+        gpg -d $2 | tar -t ;;
+    [ex] )
+        gpg -d $2 | tar -x ;;
+    * )
+        gethelp
+        exit 1 ;;
+esac
+# printf "done\n"
